### ISSUE TITLE
new pages

### ISSUE THREAD

**Issue by jrappen** [maliayas/SublimeText_Documentation#4]
Hello @maliayas,

there are a few new docs, also dev docs have been merged into stable with release of 3.2 today. On an unrelated note, any plans for tracking <https://www.sublimemerge.com/docs/>?

**Comment by maliayas** [comment]
Hello,

Thanks for the notice. Repo is manually updated now.

Tracking Sublime Merge is a good idea, so here it is: https://github.com/maliayas/SublimeMerge_Documentation
