### ISSUE TITLE
ST4xxx Docs incoming soon(ish)

### ISSUE THREAD

**Issue by jrappen** [maliayas/SublimeText_Documentation#5]
ST4xxx Docs incoming soon(ish). Compare:

![image](https://user-images.githubusercontent.com/8577450/80027000-5fec8480-84e3-11ea-8872-24474f15c755.png)

Source:

[![SublimeHQ Discord](https://img.shields.io/discord/280102180189634562?label=SublimeHQ%20Discord&logo=discord&style=flat-square)](https://discord.gg/D43Pecu)

Expect docs to show up at base url plus docs, as the main version numbers seem to be gotten rid of as SublimeHQ is moving to a time based licensing model. Build numbers are still 4xxx, though.

Find new build downloads in the announcement channel on Discord.

**Comment by maliayas** [comment]
Thanks for the notice. It seems not published yet and things sometimes take longer than planned. Can you or someone else please ping me again when it's published, as I don't follow that development channel?

**Comment by jrappen** [comment]
https://www.sublimetext.com/docs/api_reference.html#ver-dev

@maliayas Docs aren’t versioned anymore. Rest will be added later, I assume. API Reference is a nice start, though.

**Comment by maliayas** [comment]
Thanks, they are tracked now.

**Comment by jrappen** [comment]
I guess including the ST3 docs in `docs/3/` is redundant as:

* you can select the `3.x` stable releases on the pages in `docs`.
* I assume those are only there to not break links for the general public (now, before the ST4xxx Builds are released publicly).

Whatever works for you, though. Appreciate the quick update.

**Comment by maliayas** [comment]
Once they remove `/docs/3/` from the source, it will be removed here as well. I thought I should keep it for now, because it may still receive updates for a short period of time.

**Comment by jrappen** [comment]
Fair enough.

I wouldn't count on any updates for ST3, though. The last release there, Build 3211 (v3.2.2), is a stable one.
