### ISSUE TITLE
Docs updated (2022-05-27)

### ISSUE THREAD

**Issue by jrappen** [maliayas/SublimeText_Documentation#8]
Docs were updated with Build 4132.

**Comment by jrappen** [comment]
@maliayas ping

**Comment by michaelblyons** [comment]
Done with https://github.com/maliayas/SublimeText_Documentation/commit/d390a2ba818b7d43b557968b1f4408a4a42eea0d ?

**Comment by jrappen** [comment]
Sorry, yeah. Didn't try a pull cause there was no info here.

**Comment by maliayas** [comment]
Sorry guys, for some reason I haven't received email notifications from GitHub over this issue. Docs changes were fetched as you already noticed. Cheers.
